/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.programador.poo.ejercicio_26;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Federico Mamoris
 */
public class Ejercicio26 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio26
     */
    public Ejercicio26() {
        initComponents();
        ImageIcon imagen = new ImageIcon("src/main/java/com/programador/poo/assets/logo.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(jLogo.getWidth(), jLogo.getHeight(), Image.SCALE_DEFAULT));
        jLogo.setIcon(icono);
        jLogo.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLogo = new javax.swing.JLabel();
        jLName = new javax.swing.JLabel();
        jCOption = new javax.swing.JComboBox<>();
        jBResult = new javax.swing.JButton();
        jTInput = new javax.swing.JTextField();
        jLTitleInput = new javax.swing.JLabel();
        jLParcial = new javax.swing.JLabel();
        jLPais = new javax.swing.JLabel();
        jLAfip = new javax.swing.JLabel();
        jLTotalTitulo = new javax.swing.JLabel();
        jLResult = new javax.swing.JLabel();
        jLPaisNumero = new javax.swing.JLabel();
        jLAFIPNumero = new javax.swing.JLabel();
        jLTotalNumero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setPreferredSize(new java.awt.Dimension(500, 435));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 450));

        jLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLName.setText("Banco CFP");

        jCOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dolar", "Euro", "Real" }));
        jCOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCOptionActionPerformed(evt);
            }
        });

        jBResult.setLabel("Convertir");
        jBResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBResultActionPerformed(evt);
            }
        });

        jTInput.setText("Ingrese cantidad");

        jLTitleInput.setText("Cantidad de pesos argentinos");

        jLParcial.setText("Conversión valor oficial");

        jLPais.setText("Impuesto PAIS 30%");

        jLAfip.setText("Retención AFIP 35%");

        jLTotalTitulo.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLTitleInput)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCOption, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 45, Short.MAX_VALUE)
                                                .addComponent(jBResult)
                                                .addGap(73, 73, 73))
                                            .addComponent(jTInput, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLParcial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLAfip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLTotalTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(66, 66, 66)
                                                .addComponent(jLName, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(222, 222, 222))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(176, 176, 176)
                                                .addComponent(jLTotalNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLPais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(111, 111, 111)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLResult, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                            .addComponent(jLPaisNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLAFIPNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(41, 41, 41)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTitleInput)
                    .addComponent(jCOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLResult, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLParcial, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLPais, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLAfip, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLAFIPNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLPaisNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTotalTitulo)
                    .addComponent(jLTotalNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jBResult)
                .addGap(22, 22, 22))
        );

        jBResult.getAccessibleContext().setAccessibleName("jBResult");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBResultActionPerformed
        if (this.jTInput.getText().matches("^[0-9]*$")) {
            float importeParcial = 0;
            importeParcial = Float.parseFloat(this.jTInput.getText());
            float result = 0;
            result = importeParcial * 1.35f;
            this.jLAFIPNumero.setText(Float.toString(result));
            result = importeParcial * 1.3f;
            this.jLPaisNumero.setText(Float.toString(result));
            result = importeParcial * 1.65f;
            this.jLTotalNumero.setText(Float.toString(result));
            switch (this.jCOption.getSelectedItem().toString()) {
                case "Euro":
                    result = Float.parseFloat(this.jTInput.getText()) * 0.0080f;
                    this.jLResult.setText(Float.toString(result));
                    break;
                case "Dolar":
                    result = Float.parseFloat(this.jTInput.getText()) * 0.0084f;
                    this.jLResult.setText(Float.toString(result));
                    break;
                case "Real":
                    result = Float.parseFloat(this.jTInput.getText()) * 0.0042f;
                    this.jLResult.setText(Float.toString(result));
                    break;
            }
        } else {
            this.jLTotalNumero.setText("Error");

        }

    }//GEN-LAST:event_jBResultActionPerformed

    private void jCOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCOptionActionPerformed

        this.jLResult.setText("");
        this.jLAFIPNumero.setText("");
        this.jLPaisNumero.setText("");
        this.jLTotalNumero.setText("");


    }//GEN-LAST:event_jCOptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void inicializarEjercicio26() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio26.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio26.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio26.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio26.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio26().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBResult;
    private javax.swing.JComboBox<String> jCOption;
    private javax.swing.JLabel jLAFIPNumero;
    private javax.swing.JLabel jLAfip;
    private javax.swing.JLabel jLName;
    private javax.swing.JLabel jLPais;
    private javax.swing.JLabel jLPaisNumero;
    private javax.swing.JLabel jLParcial;
    private javax.swing.JLabel jLResult;
    private javax.swing.JLabel jLTitleInput;
    private javax.swing.JLabel jLTotalNumero;
    private javax.swing.JLabel jLTotalTitulo;
    private javax.swing.JLabel jLogo;
    private javax.swing.JTextField jTInput;
    // End of variables declaration//GEN-END:variables
}
